### PR TITLE
fix Prefix-tuning error in clm Float16 evaluation

### PR DESCRIPTION
**Pull request by sywangyi**

### CODE REVIEW

**Comment by sywangyi** [comment]
@pacman100  please help review

**Comment by sywangyi** [comment]
prepare_inputs_for_generation is not used in clm evaluation. so type change is missed ...

**Comment by sywangyi** [comment]
@younesbelkada

**Review by younesbelkada — COMMENTED** [review]
Hi @sywangyi thanks for the ping and the PR! 
Can you share a small reproducible script for the original issue? 🙏

**Review by pacman100 — APPROVED** [review]
Thank you @sywangyi for these fixes, LGTM! 🤗

**Pull request merged**
