### PR TITLE
FEAT Helper to check if a model is a PEFT model

### PR DESCRIPTION
**Pull request by BenjaminBossan**
After internal discussion, we decided to add this convenience function.

```python
>>> from peft.helpers import check_is_peft_model
>>> check_is_peft_model("gpt2")
False
>>> check_is_peft_model("peft-internal-testing/gpt2-lora-random")
True
>>> check_is_peft_model("peft-internal-testing/non-existing-model")
False
>>> check_is_peft_model("path/to/local/model/also/works")
```

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
Ping @stas00

**Comment by stas00** [comment]
Excellent, thank you @BenjaminBossan.

The only possible suggestion is for a different naming as `check` and `is` are both verbs, so perhaps either `is_peft_model` or `check_if_peft_model`?

I'm not sure if you have a precedent for other similar check-if utils to follow the same convention.

**Review by younesbelkada — APPROVED** [review]
Nice API ! Thanks !

**Comment by BenjaminBossan** [comment]
> The only possible suggestion is for a different naming as `check` and `is` are both verbs, so perhaps either `is_peft_model` or `check_if_peft_model`?

Good point, I renamed it to `check_if_peft_model`. My reasoning for not using `is_peft_model` is that I often want to call the variable that name in similar situations, e.g. `is_peft_model = check_if_peft_model(...); if is_peft_model: ...`

**Comment by stas00** [comment]
yes, I totally agree that:
```
is_peft_model = check_if_peft_model()
```
sounds perfect to me.

**Pull request merged**
