### PR TITLE
add the lora target modules for Mistral Models

### PR DESCRIPTION
**Pull request by pacman100**
### What does this PR do?
1. Add the lora target modules for Mistral Models

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Awesome, thanks!

**Review by younesbelkada — COMMENTED** [review]
Would it make sense to use `k_proj` & `v_proj` to be consistent with llama?

**Comment by pacman100** [comment]
> Would it make sense to use k_proj & v_proj to be consistent with llama?

Hello Younes, for all models, it is Q and V layers as per the LoRA paper.

**Review by BenjaminBossan — APPROVED** [review]
LGTM, thanks for the quick addition.

**Comment by younesbelkada** [comment]
Oops sorry, I got confused with IA3, could you also add mistral to IA3 and adalora mapping? Can be also done in a follow up PR

**Pull request merged**
