### PR TITLE
Update accelerate dependency version

### PR DESCRIPTION
**Pull request by rohithkrn**
Update accelerate version to fix -

```
File "/usr/local/lib/python3.9/dist-packages/peft/utils/other.py", line 24, in <module>                                                                     
    from accelerate.utils import is_npu_available, is_xpu_available                                                                                           
ImportError: cannot import name 'is_npu_available' from 'accelerate.utils' (/usr/local/lib/python3.9/dist-packages/accelerate/utils/__init__.py)   
```

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
Thanks for finding this issue and proposing a solution.

I checked and it seems that `is_npu_available` is already present in accelerate v0.21:

https://github.com/huggingface/accelerate/blob/v0.21.0/src/accelerate/utils/imports.py#L226

In the future, we might want to just copy these small functions into PEFT to avoid having to restrict the version of packages for just a few lines of code.

**Comment by rohithkrn** [comment]
I was on `0.20.3` version of accelerate which does not have `is_npu_available()` causing this error.

**Comment by BenjaminBossan** [comment]
Yes, it was added in 0.21 AFAICT.

**Comment by rohithkrn** [comment]
Should we set the required version > 0.21 ? Or do you have a different solution?

**Comment by BenjaminBossan** [comment]
@rohithkrn Would you be so kind to update the version?

**Comment by rohithkrn** [comment]
@BenjaminBossan updated

**Review by BenjaminBossan — APPROVED** [review]
Great, thanks!

**Review by younesbelkada — APPROVED** [review]
Thanks a lot!

**Pull request merged**
