### PR TITLE
Update on prepare_model_for_int8_training: Fix Enables Type Selection…

### PR DESCRIPTION
**Pull request by Splo2t**
… for Users

Fix: #422 
#What does this PR do?

## 1. Adds an option for users to decide whether to typecast to float32 in the prepare_model_for_int8_training function.

#422 have reported slower training speeds due to the modified prepare_model_for_int8_training function. While the updated function ensures training stability, it also introduces a trade-off where training speed is reduced as all float16 tensors are typecast to float32. To allow users to choose, we've added an fp32=True parameter to the function. When fp32 is set to True, the function performs the same role as the modified prepare_model_for_int8_training. When fp32 is set to False, float16 and bfloat16 tensors are not typecast to float32.

### CODE REVIEW

**Comment by Splo2t** [comment]
@pacman100, your review is kindly requested.

**Review by pacman100 — COMMENTED** [review]
Hello, this would not work for half-precision such as FP16/BF16. Reasons:
1. In v0.2.0 if you see, layernorms, final outputs were being converted to FP32 for training stability. One would need to bring this back and handle accordingly via the newly added `fp32` flag

**Comment by pacman100** [comment]
Alternatively, is this PR currently working as expected with half precision when using PEFT + INT8 ?

**Comment by Splo2t** [comment]
In reality, I haven't found cases where the loss converges when using `LayerNorm` weights in `fp16` while training with PEFT + INT8. It's generally known to cause problems, so I'm unsure how many cases will work correctly. However, since case #422 exists and the code modification doesn't impact the new version, I submitted this PR, believing it wouldn't be an issue.

The purpose of submitting this PR was to allow users to choose between time savings and model accuracy, considering that trade-offs might occur in certain situations.

I conducted a comparison experiment between versions 0.2.0 and 0.3.0 using the GPT-J model, with the Trainer's `fp16` and `bf16` options set to `False`. In the case of GPT-J, the variable names for `LayerNorm` layers are different, so in version 0.2.0, simply using
`model = prepare_model_for_int8_training(model)`
did not convert the `LayerNorm` layers to FP32. For cases like this, training can still proceed even if there are issues with the Loss. This would also apply to the llama model (since it doesn't contain variables with `layer_norm`).

It appears there were cases where version 0.2.0 worked correctly, so I excluded the FP32 converting portion you mentioned. Including this part would cause type errors between HalfTensor and FloatTensor.

**Comment by pacman100** [comment]
Hello, I don't think it makes sense to make changes to the `prepare_model_for_int8_training`/`prepare_model_for_kbit_training`. User can later do the changes as they like; e.g., in this gist https://gist.github.com/pacman100/1731b41f7a90a87b457e8c5415ff1c14 I have later on changed data_types of few layers to bfloat16. 

The focus currently is on having `prepare_model_for_kbit_training` work correctly in all situations and not end up giving float/half mismatches, NaN loss and so on. 

Therefore, closing this issue.

**Comment by Splo2t** [comment]
Hello,

Thank you for your feedback on the proposal. I fully understand the decision to close the issue, and I agree. 

Once again, I appreciate your suggestion and the time you have taken.

**Pull request closed without merging**
