### PR TITLE
FIX: upgrade autoawq to latest version

### PR DESCRIPTION
**Pull request by younesbelkada**
cc @BenjaminBossan

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
Would it be possible to use `pip install autoawq` and `pip install autoawq-kernels` to always stay on the latest release?

**Comment by younesbelkada** [comment]
I think this is not possible since the wheels pushed on pypi are specific to some python and cuda version that are diffferent from the one in our docker image

**Review by BenjaminBossan — APPROVED** [review]
Thanks for fixing, hopefully we have a :heavy_check_mark: in our CI tomorrow.

> I think this is not possible since the wheels pushed on pypi are specific to some python and cuda version that are diffferent from the one in our docker image

That's too bad, this means we have to constantly keep watch to update the version in the Dockerfile :-/

**Comment by BenjaminBossan** [comment]
Hmm, [still getting](https://github.com/huggingface/peft/actions/runs/8872334776/job/24356524248)
>FAILED tests/test_gpu_examples.py::PeftAwqGPUTests::test_causal_lm_training_awq - NameError: name 'awq_ext' is not defined

**Pull request merged**
