### PR TITLE
ENH: [`Docker`] Notify us when docker build pass or fail

### PR DESCRIPTION
**Pull request by younesbelkada**
As discussed offline cc @glegendre01

### CODE REVIEW

**Comment by younesbelkada** [comment]
We could use re-usable workflows here cc @glegendre01

**Comment by younesbelkada** [comment]
cc @glegendre01 @pacman100 @BenjaminBossan I tested out everything and seems to work great, this PR is ready for review!

**Review by pacman100 — APPROVED** [review]
Thank you Younes for adding this to alert when the Docker build fails!

**Review by BenjaminBossan — APPROVED** [review]
LGTM, thanks.

There is a lot of code duplication which could probably be avoided with a matrix build, but if it works as is, I'm fine.

**Comment by younesbelkada** [comment]
Yeah I agree, we could also put it in a re-usable workflow. Will do it as a follow up PR !

**Pull request merged**
