### PR TITLE
fix deepspeed zero3+prompt tuning bug. word_embeddings.weight shape i…

### PR DESCRIPTION
**Pull request by sywangyi**
…s torch.Size([0])

### CODE REVIEW

**Comment by sywangyi** [comment]
@younesbelkada please help review

**Comment by BenjaminBossan** [comment]
Thanks for this PR. Just to confirm, you tested this fix with DeepSpeed and it was necessary and sufficient to allow training the model?

**Comment by sywangyi** [comment]
yes. I have tested this fixed with deepspeed. and with the fix. the training could continue without error.

**Review by BenjaminBossan — APPROVED** [review]
Thanks a lot for identifying this issue with prompt tuning + DeepSpeed and providing the fix!

**Pull request merged**
