### PR TITLE
[docs] API example

### PR DESCRIPTION
**Pull request by stevhliu**
Adds example usage for `merge_and_unload` in the API docs.

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Looks great, thank you for this!

**Comment by younesbelkada** [comment]
@stevhliu I would also add if possible few lines here: https://moon-ci-docs.huggingface.co/docs/peft/pr_650/en/conceptual_guides/lora as this concept is sometimes hard to understand for users that are new to LoRA. There is a schema I use to explain this that is pretty much clear (see below)
lora-merged
Would it be possible to add that there maybe? 🙏 Thanks!

**Comment by stevhliu** [comment]
> I would also add if possible few lines here

Updated [here](https://moon-ci-docs.huggingface.co/docs/peft/pr_650/en/conceptual_guides/lora#merge-lora-weights-into-the-base-model), let me know if we need any more clarification!

**Review by pacman100 — APPROVED** [review]
Super helpful! Thank you @stevhliu for adding this!

**Pull request merged**
