### PR TITLE
Fix: TorchTracemalloc ruins Windows performance

### PR DESCRIPTION
**Pull request by lukaskuhn-lku**
`TorchTracemalloc` ruins the Dreambooth training performance on Windows, so that the training barely even runs. I fixed this issue by providing a parser argument `--trace_memory_allocation` that is set to `True` by default but can be turned off for Windows users. This significantly speeds up the training process.

### CODE REVIEW

**Review by pacman100 — APPROVED** [review]
Thank you @lukaskuhn-lku for making the memory tracking configurable, LGTM! 🤗

**Comment by pacman100** [comment]
Can you run `make style && make quality` to fix the code quality issues. Post that, this should be good to merge

**Comment by lukaskuhn-lku** [comment]
Thanks @pacman100! Let me fix the code formatting issues

**Comment by lukaskuhn-lku** [comment]
Sorry my bad, I will fix this import issue in an hour

**Pull request merged**
