### PR TITLE
Add docstrings for set_adapter and keep frozen

### PR DESCRIPTION
**Pull request by EricLBuehler**
Hello all,

In this PR I have added information to the docstring of `set_adapter` functions throughout the library. Specifically, I make the behavior where it sets the adapters to trainable explicit. I also provide example code to ensure that the adapters are frozen. Please see #1374.

### CODE REVIEW

**Review by BenjaminBossan — COMMENTED** [review]
Thanks for updating the docstrings with this information.

Note that the syntax for code snippets in docstrings is a bit different. Here is an example:

https://github.com/huggingface/peft/blob/97f3ed577e6f4f14e75327c897eca218abde3009/src/peft/peft_model.py#L835-L858

Could you please update the snippets accordingly?

**Comment by EricLBuehler** [comment]
I have updated the snippets, I hope that it is the correct format now?

**Comment by BenjaminBossan** [comment]
@EricLBuehler Could you please run `make style` on your changes?

**Comment by EricLBuehler** [comment]
I just ran `make style` and removed a merge conflict.

**Comment by BenjaminBossan** [comment]
Thanks for updating, but there seems to have been some issues. There is still a merge conflict here:

https://github.com/huggingface/peft/pull/1447/files#diff-ea5314dbd5288bc9963787ca71c23a3e386a62fa9e1b3a36d0d68a7c96c9c0d4

Also, it seems that other parts of the code have been linted that are not affected by your change, which should not happen. I assume that you have pulled the latest state of main and are using a recent ruff version (0.2.1)?

**Comment by EricLBuehler** [comment]
Ok, the merge conflict at your link is gone now and I ran `make style` again. Did that fix it?

**Comment by EricLBuehler** [comment]
On my end, it looks like my fork is now only 6 commits ahead and my `main` is up-to-date. Is this correct?

**Review by BenjaminBossan — APPROVED** [review]
Thanks for extending our docs with this additional info. LGTM.

**Comment by EricLBuehler** [comment]
Thank you! Glad to help.

**Pull request merged**
