### PR TITLE
Allow trust_remote_code for tokenizers when loading AutoPeftModels

### PR DESCRIPTION
**Pull request by OfficialDelta**

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Looks good! IMO we should allow that for full flexibility

**Comment by BenjaminBossan** [comment]
@OfficialDelta Could you please run `make style` (or manually add the missing trailing comma)?

**Review by pacman100 — COMMENTED** [review]
Thank you @OfficialDelta for adding this, LGTM to merge once the quality issues are resolved via `make style && make quality`.

**Comment by OfficialDelta** [comment]
@pacman100 @BenjaminBossan I ran make style && make quality and committed the changes.

**Review by younesbelkada — APPROVED** [review]
Thanks !

**Pull request merged**
