### PR TITLE
Fix: Multiple adapters with bnb layers

### LINKED ISSUE #1239: error while loading lora
### System Info

A800, multiple loras

### Who can help?

_No response_

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```python
model = AutoModelForCausalLM.from_pretrained(
    "Qwen-7B-Chat-Int4",
    device_map="auto",
    trust_remote_code=True
).eval()
from peft import PeftModel
model = PeftModel.from_pretrained(model,'lora1', adapter_name="lora1",device_map="cuda")
model.load_adapter('lora2',adapter_name = 'lora2')
```

#########
it happens error

```
File /home/anaconda3/envs/lib/python3.10/site-packages/peft/peft_model.py:686, in PeftModel.load_adapter(self, model_id, adapter_name, is_trainable, **kwargs)
    684     else:
    685         peft_config.inference_mode = not is_trainable
--> 686     self.add_adapter(adapter_name, peft_config)
    688 adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs)
    690 # load the weights into the model

File /home/anaconda3/envs/lib/python3.10/site-packages/peft/peft_model.py:616, in PeftModel.add_adapter(self, adapter_name, peft_config)
    614     else:
    615         self.peft_config[adapter_name] = peft_config
--> 616         self.base_model.inject_adapter(self.base_model.model, adapter_name)
    617 except Exception:  # somthing went wrong, roll back
    618     if adapter_name in self.peft_config:

File /home/anaconda3/envslib/python3.10/site-packages/peft/tuners/tuners_utils.py:252, in BaseTuner.inject_adapter(self, model, adapter_name)
    245     parent, target, target_name = _get_submodules(model, key)
    247     optional_kwargs = {
    248         "loaded_in_8bit": getattr(model, "is_loaded_in_8bit", False),
    249         "loaded_in_4bit": getattr(model, "is_loaded_in_4bit", False),
    250         "current_key": key,
    251     }
--> 252     self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
    254 if not is_target_modules_in_base_model:
    255     raise ValueError(
    256         f"Target modules {peft_config.target_modules} not found in the base model. "
    257         f"Please check the target modules and try again."
    258     )

File /home/anaconda3/envs/lib/python3.10/site-packages/peft/tuners/lora/model.py:200, in LoraModel._create_and_replace(self, lora_config, adapter_name, target, target_name, parent, current_key, **optional_kwargs)
    192     target.update_layer(
    193         adapter_name,
    194         r,
   (...)
    197         lora_config.init_lora_weights,
    198     )
    199 else:
--> 200     new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
    201     if adapter_name != self.active_adapter:
    202         # adding an additional adapter: it is not automatically trainable
    203         new_module.requires_grad_(False)

File /homeanaconda3/envs/lib/python3.10/site-packages/peft/tuners/lora/model.py:296, in LoraModel._create_new_module(lora_config, adapter_name, target, **kwargs)
    294 elif AutoGPTQQuantLinear is not None and isinstance(target_base_layer, AutoGPTQQuantLinear):
    295     new_module = QuantLinear(target, adapter_name, **kwargs)
--> 296     print(target.qweight)
    297     #target.weight = target.qweight
    298 elif isinstance(target_base_layer, torch.nn.Embedding):

File /home/anaconda3/envs/lib/python3.10/site-packages/torch/nn/modules/module.py:1614, in Module.__getattr__(self, name)
   1612     if name in modules:
   1613         return modules[name]
-> 1614 raise AttributeError("'{}' object has no attribute '{}'".format(
   1615     type(self).__name__, name))


### Expected behavior

load multiple loras to one model by using model.load_adapter

### PR DESCRIPTION
**Pull request by BenjaminBossan**
Resolves #1239

## Description

Fixes a bug that led to an error when loading multiple adapters into a
peft model that uses bnb layers.

## Notes

I tested this locally on GPU and tests pass for me.

## Implementation

While working on this, I thought we could make a simplification to our
layer code. Right now, we have code like this inside of
`_create_and_replace`:

```python
    if isinstance(target, conv2d):
        target.update_layer_conv2d(...)
    elif isinstance(target, embedding):
        target.update_layer_embedding(...)
    elif ...
```

If we move the `update_layer*` methods from `LoraLayer` to the subclasses,
i.e. `Linear`, `Embedding`, etc., and give them all the same name (i.e.
`update_layer_embedding` => `update_layer`), we could simplify the code
above to:

```python
    if isinstance(target, LoraLayer):
        target.update_layer(...)
```

Additionally, it makes more sense to me that the code for
`update_layer_embedding` lives inside of `Embedding`, not the parent class.
If you agree, I could work on that in a separate PR.

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Thank you !

**Comment by ChrisXULC** [comment]
while I tried to use this solution to load multiple lora in peft model, it appear a error. 

[245](https://vscode-remote+ssh-002dremote-002b10-002e20-002e152-002e75.vscode-resource.vscode-cdn.net/home/qjsys/xlc/%E9%87%8F%E5%8C%96/~/anaconda3/envs/wbl_qwen/lib/python3.10/site-packages/peft/tuners/tuners_utils.py:245)     parent, target, target_name = _get_submodules(model, key)
    [247](https://vscode-remote+ssh-002dremote-002b10-002e20-002e152-002e75.vscode-resource.vscode-cdn.net/home/qjsys/xlc/%E9%87%8F%E5%8C%96/~/anaconda3/envs/wbl_qwen/lib/python3.10/site-packages/peft/tuners/tuners_utils.py:247)     optional_kwargs = {
    [248](https://vscode-remote+ssh-002dremote-002b10-002e20-002e152-002e75.vscode-resource.vscode-cdn.net/home/qjsys/xlc/%E9%87%8F%E5%8C%96/~/anaconda3/envs/wbl_qwen/lib/python3.10/site-packages/peft/tuners/tuners_utils.py:248)         "loaded_in_8bit": getattr(model, "is_loaded_in_8bit", False),
    [249](https://vscode-remote+ssh-002dremote-002b10-002e20-002e152-002e75.vscode-resource.vscode-cdn.net/home/qjsys/xlc/%E9%87%8F%E5%8C%96/~/anaconda3/envs/wbl_qwen/lib/python3.10/site-packages/peft/tuners/tuners_utils.py:249)         "loaded_in_4bit": getattr(model, "is_loaded_in_4bit", False),
    [250](https://vscode-remote+ssh-002dremote-002b10-002e20-002e152-002e75.vscode-resource.vscode-cdn.net/home/qjsys/xlc/%E9%87%8F%E5%8C%96/~/anaconda3/envs/wbl_qwen/lib/python3.10/site-packages/peft/tuners/tuners_utils.py:250)         "current_key": key,
...
   [1672](https://vscode-remote+ssh-002dremote-002b10-002e20-002e152-002e75.vscode-resource.vscode-cdn.net/home/qjsys/xlc/%E9%87%8F%E5%8C%96/~/anaconda3/envs/wbl_qwen/lib/python3.10/site-packages/torch/nn/modules/module.py:1672)     buffers[name] = value
   [1673](https://vscode-remote+ssh-002dremote-002b10-002e20-002e152-002e75.vscode-resource.vscode-cdn.net/home/qjsys/xlc/%E9%87%8F%E5%8C%96/~/anaconda3/envs/wbl_qwen/lib/python3.10/site-packages/torch/nn/modules/module.py:1673) else:
-> [1674](https://vscode-remote+ssh-002dremote-002b10-002e20-002e152-002e75.vscode-resource.vscode-cdn.net/home/qjsys/xlc/%E9%87%8F%E5%8C%96/~/anaconda3/envs/wbl_qwen/lib/python3.10/site-packages/torch/nn/modules/module.py:1674)     super().__setattr__(name, value)

AttributeError: can't set attribute 'weight'

and it seems to work if I modify the code in _create_new_module this way:

elif AutoGPTQQuantLinear is not None and isinstance(target_base_layer, AutoGPTQQuantLinear):
        new_module = QuantLinear(target, adapter_name, **kwargs)
        ###xlc
        if target == None:
            target.weight = target_base_layer.qweight
        else:
            target = target_base_layer
            target.weight = target_base_layer.qweight

**Comment by BenjaminBossan** [comment]
@ChrisXULC Thanks for reporting. Do you have some code to reproduce the error?

**Review by pacman100 — APPROVED** [review]
Thank you @BenjaminBossan for fixing the issue when using multiple adapters with bnb layers, nice tests! LGTM! 🚀

**Comment by ChrisXULC** [comment]
> @ChrisXULC Thanks for reporting. Do you have some code to reproduce the error?

@BenjaminBossan it could be reproduce while trying to load multiple loras into Qwen 7b int 4 model. before loading loras, I have modified the anaconda3/envs/lib/python3.10/site-packages/peft/tuners/lora/model.py like you did.

model = AutoModelForCausalLM.from_pretrained(
    "/home/models/qwen/Qwen-7B-Chat-Int4",
    device_map="auto",
    trust_remote_code=True
    # use_cache_quantization=True,
    #  use_cache_kernel=True,
    # use_flash_attn=False
).eval()


model = PeftModel.from_pretrained(model,'/home//models/quantized_model_lora', adapter_name="23",device_map="cuda", load_in_4bit=True)
model.load_adapter('/home/lora_all/quantized_model_vul',adapter_name = '22')

**Comment by BenjaminBossan** [comment]
@ChrisXULC Thanks a lot. The issue should be fixed with the latest commit. I omitted the `if target == None:` guard in from your suggestion, I don't think that can happen, but LMK if I'm wrong.

**Comment by ChrisXULC** [comment]
@BenjaminBossan I have changed it to target.qweight=target_base_layer.qweight，I think it should be ok

**Comment by BenjaminBossan** [comment]
@ChrisXULC Thanks for checking. If you also have time to check PEFT from this branch, that would be fantastic.

**Comment by ChrisXULC** [comment]
@BenjaminBossan cool!

**Comment by BenjaminBossan** [comment]
Tests are green now after merging #1252, I'll merge this one too.

**Pull request merged**
