### PR TITLE
Allow multiple transformer layer types in peft.utils.other.fsdp_auto_wrap_policy

### PR DESCRIPTION
**Pull request by fleonce**
What does this PR do?

It introduces an optional parameter `transformer_cls_to_wrap` to `peft.utils.other.fsdp_auto_wrap_policy` which allows an additional optional configuration of transformer layer classes.

BART Models for example have two different types of transformer blocks, BartEncoderLayer and BartDecoderLayer. Configuration via the environment variable `FSDP_TRANSFORMER_CLS_TO_WRAP` is not possible in this case.

### CODE REVIEW

**Comment by fleonce** [comment]
I moved the collection of all possible transformer layer types out of the creation of the partial, to maintain a better readability and added an additional check when resolving via the environment variable, to ensure only not `None` types get through to the partial call. Otherwise, if one specifies only block types via the new parameter and not via the environment variable, the creation of the FSDP Model would fail down the line.

It might be a good Idea to include a warning when neither the new parameter nor the environment variable have been used as well as when the specified model type cannot be found inside the given model.

**Comment by fleonce** [comment]
As I cannot request for a review, im not familiar with that functionality, I will just cc @pacman100

**Comment by pacman100** [comment]
Hello, it is possible to provide multiple module names to `FSDP_TRANSFORMER_CLS_TO_WRAP`, as mentioned in the docs here https://huggingface.co/docs/accelerate/usage_guides/fsdp

> user specifies comma-separated string of transformer layer class names (case-sensitive) to wrap ,e.g, 
`BertLayer`, `GPTJBlock`, `T5Block`, `BertLayer,BertEmbeddings,BertSelfOutput`...

**Comment by fleonce** [comment]
Hello, while this is true, I believe it will not work specifying them as a list, as the `FullyShardedDataParallelPlugin.get_module_class_from_name` will in the case you mentioned return a list, however this will not work when the transformer wrapper policy gets created. Specifying a list as an entry to the list of transformer layer classes will result in an error.

[L176](https://github.com/huggingface/peft/blob/main/src/peft/utils/other.py#L176)

**Comment by pacman100** [comment]
Hello @fleonce, please resolve the code quality issues as well as the conflicts. The logic in the PR makes sense, thank you.

**Comment by fleonce** [comment]
Hi @pacman100 the code quality issues should be fixed now.

**Pull request closed without merging**
