### PR TITLE
chore(type): annotate that peft does contains type hints

### PR DESCRIPTION
**Pull request by aarnphm**
This helps type checker to know that `peft` indeed does provide type hints.

Signed-off-by: Aaron <29749331+aarnphm@users.noreply.github.com>

### CODE REVIEW

**Comment by aarnphm** [comment]
See https://peps.python.org/pep-0561/

**Review by pacman100 — APPROVED** [review]
Thank you @aarnphm for adding this, LGTM!

**Comment by BenjaminBossan** [comment]
A question for my understanding @aarnphm : The majority of the code base is untyped at the moment. Would this be problematic or is it just ignored when adding `py.typed`?

**Comment by aarnphm** [comment]
Adding `py.typed` would address the following:

```prolog
/home/runner/work/OpenLLM/OpenLLM/src/openllm/_configuration.py
  /home/runner/work/OpenLLM/OpenLLM/src/openllm/_configuration.py:101:12 - error: Import "peft" could not be resolved (reportMissingImports)
```

However, I'm not sure what's the plan for typing with `peft`, but I believe that adding this is one of the first step towards fully typed the library. It would be problematic if you are using strict type checking, but I think for most python library, it is impossible to make strict type anw.

**Comment by pacman100** [comment]
Thank you @aarnphm for the explanation!

**Review by BenjaminBossan — APPROVED** [review]
LGTM

**Comment by aarnphm** [comment]
qq: Is there a release date for 0.4.0?

**Pull request merged**
