### PR TITLE
Decrease memory usage of `merge_and_unload`

### PR DESCRIPTION
**Pull request by snarayan21**
Addresses #1939

### CODE REVIEW

**Comment by snarayan21** [comment]
@BenjaminBossan Would be great to get your approval here!

**Comment by BenjaminBossan** [comment]
I checked the PEFT code on why we merge this way. Turns out we used to do it in-place but this PR changed it: #1372. IMO merging should not affect the error reported there, so I think we can undo the change, but I wanted to provide the necessary context.

Could you please also update the other merge functions?

https://github.com/huggingface/peft/blob/ba75bb14d115dfdff3294674d82d8097319ed74e/src/peft/tuners/lora/layer.py#L671
https://github.com/huggingface/peft/blob/ba75bb14d115dfdff3294674d82d8097319ed74e/src/peft/tuners/lora/layer.py#L927

Thanks.

I plan to make a release soon, aiming for tomorrow.

**Comment by snarayan21** [comment]
@BenjaminBossan thanks for the pointers, found some additional places where this change is also needed.
 And yeah since #1372 was a training time error making this fix for merging adapters shouldn't be applicable.
 
 Hope this looks good to you.

**Comment by snarayan21** [comment]
A release tomorrow with this fix would be ideal.

**Comment by BenjaminBossan** [comment]
Strange that Windows CI is consistently failing. Hard to imagine that this is caused by the PR but I'm investigating further (but don't have a Windows machine myself). Hopefully this is just a temporary issue.

**Comment by snarayan21** [comment]
Yeah quite weird:
```
The directory name is invalid: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpv612vppk\\model.safetensors'
```

**Comment by BenjaminBossan** [comment]
Okay, so the same Windows errors as in #1947, which has no code changes.

**Review by BenjaminBossan — APPROVED** [review]
Thanks for restoring the more memory efficient merging behavior. A release tomorrow should be possible.

**Pull request merged**
