### PR TITLE
FIX Honor HF_HUB_OFFLINE mode if set by user

### LINKED ISSUE #1452: peft/utils/save_and_load.py try to connect to the hub even when HF_HUB_OFFLINE=1
### System Info

peft 0.8.2
axolotl v0.4.0

export HF_DATASETS_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export HF_HUB_OFFLINE=1

### Who can help?

_No response_

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

When I am FT my models on a GPU offline using lora and peft with axolotl library, I get an error from peft/utils/save_and_load.py", line 146, in get_peft_model_state_dict
    has_remote_config = file_exists(model_id, "config.json")
The function try to connect to the HUB before saving the checkpoint locally, which make crash the run and lose the FT model.

Here is the full error message:

`Traceback (most recent call last):
  File "/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.9.12/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.9.12/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfsdswork/projects/rech/vqt/ule33dt/axolotl/src/axolotl/cli/train.py", line 59, in <module>
    fire.Fire(do_cli)
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/gpfsdswork/projects/rech/vqt/ule33dt/axolotl/src/axolotl/cli/train.py", line 35, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
  File "/gpfsdswork/projects/rech/vqt/ule33dt/axolotl/src/axolotl/cli/train.py", line 55, in do_train
    return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
  File "/gpfsdswork/projects/rech/vqt/ule33dt/axolotl/src/axolotl/train.py", line 163, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/transformers/trainer.py", line 1561, in train
    return inner_training_loop(
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/transformers/trainer.py", line 1968, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/transformers/trainer.py", line 2340, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/transformers/trainer.py", line 2416, in _save_checkpoint
    self.save_model(staging_output_dir, _internal_call=True)
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/transformers/trainer.py", line 2927, in save_model
    self._save(output_dir)
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/transformers/trainer.py", line 2999, in _save
    self.model.save_pretrained(
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/peft/peft_model.py", line 216, in save_pretrained
    output_state_dict = get_peft_model_state_dict(
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/peft/utils/save_and_load.py", line 146, in get_peft_model_state_dict
    has_remote_config = file_exists(model_id, "config.json")
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 2386, in file_exists
    get_hf_file_metadata(url, token=token)
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1631, in get_hf_file_metadata
    r = _request_wrapper(
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 385, in _request_wrapper
    response = _request_wrapper(
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/linkhome/rech/genrqo01/ule33dt/.local/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 78, in send
    raise OfflineModeIsEnabled(
huggingface_hub.utils._http.OfflineModeIsEnabled: Cannot reach https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1/resolve/main/config.json: offline mode is enabled. To disable it, please unset the `HF_HUB_OFFLINE` environment variable.`

I manage to fix the bug by commenting those lines in save_and_load.py:
`if model_id is not None:
            try:
                has_remote_config = file_exists(model_id, "config.json")
            except (HFValidationError, EntryNotFoundError):
                warnings.warn(
                    f"Could not find a config file in {model_id} - will assume that the vocabulary was not modified."
                )
                has_remote_config = False`

### Expected behavior

It seems that `file_exists(model_id, "config.json")` should not call the hub when the variable 'export `HF_HUB_OFFLINE=1` is set

### PR DESCRIPTION
**Pull request by BenjaminBossan**
Resolves #1452

If users enable offline mode, don't perform checks for files on HF Hub, as they would fail.

### CODE REVIEW

**Review by pacman100 — APPROVED** [review]
Thank you @BenjaminBossan!

**Comment by BenjaminBossan** [comment]
> However, this won't handle the timeout scenarios like the recent one, right?

No, I don't think so. We could try to add that by including the corresponding exception. Do you know which one that is?

**Comment by powerjohnnyli** [comment]
@pacman100  Thanks for this change, can we get a patch release with this included for easy installation using pip? What's the expected timeline on this?

**Comment by edamamez** [comment]
Do we know when this will be included in a release?

**Comment by BenjaminBossan** [comment]
> Do we know when this will be included in a release?

We're finishing up a last few PRs, after that we should be ready for a release. We aim for this week.

**Pull request merged**
