### PR TITLE
Fix model argument issue (#1198)

### PR DESCRIPTION
**Pull request by ngocbh**
A quick fix to issue #1198 that makes sure one model is used throughout `inject_adapter` function in `BaseTuner`.

### CODE REVIEW

**Comment by ngocbh** [comment]
The reason I want to `_mark_only_adapters_as_trainable` can also work without passing the model argument is the `BaseTuner` is already a model. So if we want to use this function outside the class we might have to call `model._mark_only_adapters_as_trainable(model.model)`. I think this is the main use case of this function outside the class. But calling like this seems a little bit weird to me. That's why I let this function work without passing the model argument. What do you think? 

If you still prefer to make `model` a required argument, I will change it back.

**Comment by BenjaminBossan** [comment]
> I think this is the main use case of this function outside the class.

I'm not quite sure I understand this. Do you mean that PEFT users may want to call `model._mark_only_adapters_as_trainable`? If that is so, I think we should add an explicit method/function for that, as `_mark_only_adapters_as_trainable` is supposed to be "private" and thus not called directly in user code.

**Comment by ngocbh** [comment]
Sorry for the delay, I fixed the issue according to your suggestions.

**Review by BenjaminBossan — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
