### PR TITLE
ENH fix library interface

### PR DESCRIPTION
**Pull request by bluenote10**
This PR fixes peft's library interface to adhere to the typing specification as described in #2261.

The easiest way to fix the interface was basically to remove the existing `flake8: noqa` lints, which exactly have lead to a non-spec conforming interface. After enabling linting of these files, ruff ensures that the symbols _must be used_ e.g. within `__all__`. Thus it is technically impossible to import a symbol, but forget to add it to `__all__`, because ruff will report that.

Note that when enabling linting these files, ruff would also like to re-order the imports, because they are currently not ordered properly. To simplify the reviewing, I have temporarily added a local `# noqa: I001` suppression so that ruff does not _yet_ insist on the proper order. This makes it easier for you to see that the exported symbols have not changed. The only symbol that I have removed is `VBLoRAConfig`, because it was actually appearing twice in the list, and ruff will also complain about the redundant double import.

After merging this PR, I would then open a follow-up PR that removes these `# noqa: I001` suppressions, along with the required import re-orderings. In this follow-up PR the listed symbols in `__all__` will remain stable (I have already sorted them alphabetically). So in that second PR, there is no mental effort required that the re-ordering is correct :wink: -- ruff will ensure that the imported and exported symbols have to match.

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
Thanks for the PR and for laying out your plan. This sounds reasonable to me and I'm happy to hear that ruff enforces this, so that the lists are staying up-to-date.

Just one question regarding the sorting: Usually, capital letters are ordered to be before lower case letters. So e.g. for `utils/__init__.py`, I'd expect the list to be `['CONFIG_NAME', 'INCLUDE_LINEAR_LAYERS_SHORTHAND', 'ModulesToSaveWrapper', ...]`. Or is the logic here different for some reason?

**Comment by bluenote10** [comment]
> Just one question regarding the sorting: Usually, capital letters are ordered to be before lower case letters.

To clarify: I believe currently ruff only cares about the order of the imports (`I001`), but I don't think it cares about the order of the exports in `__all__` (there may be another optional rule for that -- but I haven't checked that yet). So there is currently some freedom in how to order the symbols in `__all__`. What I did to avoid having to sort them manually was to rely on the VSCode feature (select the rows, go to command palette, and do "sort lines ascending"). So this just happens to be the ordering semantics of VSCode. If you prefer, I could manually re-order them. However, in case other developers would also use this VSCode feature, it might be easier to go for that way of ordering to allow for automation.

**Comment by BenjaminBossan** [comment]
> I found the ruff rule to order `__all__`

How about for this PR, only order the newly added `__all__`s according to that logic, we can leave the others for a later PR.

**Comment by bluenote10** [comment]
> How about for this PR, only order the newly added __all__s according to that logic, we can leave the others for a later PR.

Yep that sounds good. In fact, I simply temporarily enabled `RUF022`, let ruff do its thing to get the sorting right, and only committed the changes in the `__init__.py` affected by this PR.

**Pull request merged**
