### PR TITLE
[WIP] FIX for disabling adapter, adding tests

### PR DESCRIPTION
**Pull request by BenjaminBossan**
As discussed internally.

This PR deals with some issues with disabling adapter:

- typo in `active.adapter`
- moving the prompt encoder to the correct device for prompt learning
- when using prompt learning + `generate`, disabling did not work

For the second point, there is a somewhat ugly fix in place for now, pending a more comprehensive refactor (a comment was added to that effect).

The more difficult part was adding a bunch of tests to check if disabling adapters actually works. I did that but unfortunately, of the 41 tests, 6 are still failing. The error is always that the outputs after disabling the adapter are not identical to the outputs of the base model. Sometimes, they are partly identical, sometimes, they are identical to the peft model with adapters active.

After hours of debugging, I could fix many tests but not those last few. Any help would be welcome @pacman100 @younesbelkada

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
Update: I extended the tests to include testing that disabling adapters works after merging. Unfortunately, this leads to even more tests failing.

**Review by younesbelkada — COMMENTED** [review]
Great new test! 
I made https://github.com/BenjaminBossan/peft/pull/2 that should solve the decoder models test 🙏 Let me know WDYT

**Comment by younesbelkada** [comment]
@BenjaminBossan thanks a lot for digging and debugging this ! 
I have experienced a similar issue in the past with T5 models, this might be due to the way the weights of the base model are initialized, if you model weights have a distribution around very low values you should multiply all the weights of the tiny model with a large factor and push it for example here: https://huggingface.co/peft-internal-testing and use that model instead. Let me know if you need help for that !

**Comment by BenjaminBossan** [comment]
@younesbelkada Thanks for the tip. However, it turned out to be something else.

The first issue was that the parametrization for the SD test did not propagate the config kwargs to the individual configs of text encoder and unet. That means that `init_lora_weights=False` was not present in the individual configs. This is now fixed.

The second issue was that there seems to be a tiny amount of randomness in the output, e.g. sometimes 1 pixel of 50000 being different after disabling adapters. The test is now more robust to those tiny deviations. I have tested it locally 10 times without error, so I think it is now robust enough and not too flaky.

**Review by younesbelkada — APPROVED** [review]
Thanks for all your work on this and for all the explanations !

**Comment by BenjaminBossan** [comment]
Just to summarize the state of the PR:

- A couple of bugs fixed
- Tests added
- Following tests still not working:
  - adaption prompt
  - seq2seq with prompt tuning/prompt encoding
  - stable diffusion is a little bit flaky but test is hopefully robust enough

I think this is an improvement over the current situation and can be merged if @pacman100 approves.

**Review by pacman100 — APPROVED** [review]
Thank you @BenjaminBossan for all the work in fixes and tests! 🤗

**Pull request merged**
