### PR TITLE
add: example on fine-tuning for image classification.

### PR DESCRIPTION
**Pull request by sayakpaul**
Closes https://github.com/huggingface/peft/issues/44

However, this PR is blocked by https://github.com/huggingface/peft/issues/57

I hope the text used in the Colab Notebook added in this PR could serve as a reference for the future examples :)

### CODE REVIEW

**Comment by sayakpaul** [comment]
@younesbelkada @pacman100 this PR is ready for review :)

**Comment by pacman100** [comment]
Really detailed and a great example notebook! 🔥

Thank you for working on this and it indeed serves as a reference for future examples 🤗. Good to merge 🚀

**Comment by sayakpaul** [comment]
Thank you for all your guidance! Feel free to merge at your convenience, I don't have rights.

Currently working om semantic segmentation :)

**Review by younesbelkada — APPROVED** [review]
Amazing notebook @sayakpaul ! thanks a lot for working on this 💯

**Pull request merged**
