### PR TITLE
add accelerate example for DDP and FSDP in sequence classification fo…

### PR DESCRIPTION
**Pull request by sywangyi**
…r non-lora case

### CODE REVIEW

**Comment by sywangyi** [comment]
@pacman100 please help review.

**Review by pacman100 — COMMENTED** [review]
Thank you @sywangyi for adding this example for non-lora methods, is FSDP resulting in decrease in memory usage, for me the last time I checked it wasn't the case

**Comment by sywangyi** [comment]
yes, I see memory decrease in FSDP. I finetune llama 7b with 2-GPUs (RTX8000) using p-tuning, if FSDP is not used, DDP will be crashed because of OOM if training batch size is set to 8, while no crash with fsdp. and if cpu offload is used, the memory will decrease more comparing with no cpu offload in FSDP. but you should apply [****](https://github.com/huggingface/peft/pull/352) to use cpu offload in fsdp.

**Review by pacman100 — APPROVED** [review]
Thank you @sywangyi for adding this example and confirming that using FSDP leads to memory savings with non LoRA methods, LGTM! 🤗

**Pull request merged**
