### PR TITLE
feat: add type hints

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
This PR aims to add some better type hints.

### CODE REVIEW

**Comment by SauravMaheshkar** [comment]
Request for Review: @pacman100

**Comment by SauravMaheshkar** [comment]
Request for Review 😅

**Review by younesbelkada — APPROVED** [review]
Thanks for adding the typehints and making the code more readable!

**Comment by younesbelkada** [comment]
@SauravMaheshkar can you push an empty commit to trigger CI? You might need to run `make style && make quality` as well

**Comment by SauravMaheshkar** [comment]
> @SauravMaheshkar can you push an empty commit to trigger CI? You might need to run `make style && make quality` as well

Ran `make style && make quality`, no changes so I pushed a empty commit.

**Review by younesbelkada — APPROVED** [review]
Thanks again !

**Pull request merged**
