### PR TITLE
FIX Make special LoRA inits DeepSpeed compatible

### PR DESCRIPTION
**Pull request by BenjaminBossan**
Resolves https://github.com/huggingface/accelerate/issues/2886

Possibly resolves
https://github.com/huggingface/peft/issues/896#issuecomment-2172455458

Some LoRA init methods need to access the base layer weight. Getting this access can fail or stall in distributed settings. For DeepSpeed, the weight is now gathered before trying to access it.

Note: Without DeepSpeed, this is a no-op and should thus not have any disadvantage. We don't have DS in our CI, so this is not tested.

I also made some small changes to OLoRA init to use `self.get_base_layer()` instead of `self.base_layer`.

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
ping @tokenizer-decode as there are some slight changes to OLoRA.

**Review by SunMarc — APPROVED** [review]
LGTM ! Maybe we can leave a comment on why we added that for these inits since we don't do it for other inits

**Comment by tokenizer-decode** [comment]
Could you explain to me why `self.get_base_layer()` rather than `self.base_layer`?  No mutation to base weights occured at that part so I'd assume both should return the same? How did this solve the problem? I am surprised.

**Comment by BenjaminBossan** [comment]
> Could you explain to me why `self.get_base_layer()` rather than `self.base_layer`? No mutation to base weights occured at that part so I'd assume both should return the same?

The reason why we have `get_base_layer()` is that we support nesting LoRA adapters and other adapter types. Calling the method ensures we really get back the "original" base layer. When there is no nesting, both approaches are indeed the same.

> How did this solve the problem? I am surprised.

This change is not related to the DeepSpeed issue, that's what I wanted to convey when I wrote "I also made some small changes to OLoRA".

**Comment by tokenizer-decode** [comment]
Oh now I see. Thanks for notifying. Looks good.

**Pull request merged**
