### PR TITLE
Fix doc for semantic_segmentation_lora

### PR DESCRIPTION
**Pull request by raghavanone**
Fixes https://github.com/huggingface/transformers/issues/25801

### CODE REVIEW

**Review by BenjaminBossan — COMMENTED** [review]
Thanks for fixing this deprecation. Does this line also need to be adjusted?

https://github.com/huggingface/peft/blob/7d99466446d65219a401a2c64f1d84d1b1be31b4/docs/source/task_guides/semantic_segmentation_lora.mdx#L183

I also found uses of `reduce_label` in this notebook:

https://github.com/huggingface/peft/blob/main/examples/semantic_segmentation/semantic_segmentation_peft_lora.ipynb

**Comment by raghavanone** [comment]
> 

Yes, I missed those lines.

**Comment by BenjaminBossan** [comment]
Thanks for providing the additional fixes. Did you do further changes to the notebook? The diff looks quite big.

**Comment by raghavanone** [comment]
> Thanks for providing the additional fixes. Did you do further changes to the notebook? The diff looks quite big.

Yeah, I open it in a editor and it had added lot of metadata, now fixed.

**Review by BenjaminBossan — APPROVED** [review]
LGTM, thanks for fixing!

**Pull request merged**
