### PR TITLE
fix ptun and prompt tuning generation issue

### PR DESCRIPTION
**Pull request by sywangyi**

### CODE REVIEW

**Comment by sywangyi** [comment]
@pacman100

**Comment by sywangyi** [comment]
Traceback (most recent call last):
  File "/home/ywan171/alpaca/HuggingFace/alpaca/generate_output.py", line 80, in <module>
    print(evaluate(instruction))
  File "/home/ywan171/alpaca/HuggingFace/alpaca/generate_output.py", line 66, in evaluate
    generation_output = model.generate(
  File "/home/ywan171/alpaca/peft/src/peft/peft_model.py", line 790, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/home/ywan171/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ywan171/alpaca/transformers/src/transformers/generation/utils.py", line 1607, in generate
    return self.beam_search(
  File "/home/ywan171/alpaca/transformers/src/transformers/generation/utils.py", line 2904, in beam_search
    outputs = self(
  File "/home/ywan171/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ywan171/alpaca/transformers/src/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/home/ywan171/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ywan171/alpaca/transformers/src/transformers/models/llama/modeling_llama.py", line 528, in forward
    position_ids = position_ids.view(-1, seq_length).long()
RuntimeError: shape '[-1, 76]' is invalid for input of size 184

**Comment by younesbelkada** [comment]
Also could you give a brief description of the issue you encoutered before opening the PR and how this PR fixes it?

**Comment by sywangyi** [comment]
Hi, I use P-tuning to finetune alpaca. when I use the output p-tun model to generate the output. there's coredump.
calltrace is 

File "/home/ywan171/alpaca/HuggingFace/alpaca/generate_output.py", line 80, in
print(evaluate(instruction))
File "/home/ywan171/alpaca/HuggingFace/alpaca/generate_output.py", line 66, in evaluate
generation_output = model.generate(
File "/home/ywan171/alpaca/peft/src/peft/peft_model.py", line 790, in generate
outputs = self.base_model.generate(**kwargs)
File "/home/ywan171/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/home/ywan171/alpaca/transformers/src/transformers/generation/utils.py", line 1607, in generate
return self.beam_search(
File "/home/ywan171/alpaca/transformers/src/transformers/generation/utils.py", line 2904, in beam_search
outputs = self(
File "/home/ywan171/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/home/ywan171/alpaca/transformers/src/transformers/models/llama/modeling_llama.py", line 688, in forward
outputs = self.model(
File "/home/ywan171/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/home/ywan171/alpaca/transformers/src/transformers/models/llama/modeling_llama.py", line 528, in forward
position_ids = position_ids.view(-1, seq_length).long()
RuntimeError: shape '[-1, 76]' is invalid for input of size 184

and I found same error in prompt-tuning as well. I debug and found the position id and attention mask is incorrect in this case.
and I see the disposal of attention mask and position id is in generate() API, but in my case, the kwargs in generate() does not contain it, so I move them to prepare_inputs_for_generation to cover my case.

**Comment by sywangyi** [comment]
PR updated to fix test failure

**Comment by StefanHeng** [comment]
I also need `p-tuning` and `prompt tuning` supported for generation. I'm using the seq2seq LM `google/flan-t5-base`. Looks like this PR only works on the causal LM case.

**Comment by sywangyi** [comment]
> I also need `p-tuning` and `prompt tuning` supported for generation. I'm using the seq2seq LM `google/flan-t5-base`. Looks like this PR only works on the causal LM case.

yes, same change need to apply to PeftModelForSeq2SeqLM

**Comment by sywangyi** [comment]
@pacman100 , could you help review it? we use ptun model for CLM generation. w/o this PR, it will coredump.

**Review by pacman100 — APPROVED** [review]
Thank you @sywangyi for the fixes! tested locally to make sure it is working fine 🤗

**Pull request merged**
