### PR TITLE
fix prompt learning error if resize_token_embeddings is called for pe…

### PR DESCRIPTION
**Pull request by sywangyi**
…ft model

### CODE REVIEW

**Comment by sywangyi** [comment]
@pacman100 please help review

**Comment by sywangyi** [comment]
Traceback (most recent call last):
  File "/mnt/disk3/wangyi/HuggingFace/alpaca/train.py", line 263, in <module>
    train()
  File "/mnt/disk3/wangyi/HuggingFace/alpaca/train.py", line 253, in train
    trainer.train()
  File "/mnt/disk3/wangyi/transformers/src/transformers/trainer.py", line 1696, in train
    return inner_training_loop(
  File "/mnt/disk3/wangyi/transformers/src/transformers/trainer.py", line 1972, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/mnt/disk3/wangyi/transformers/src/transformers/trainer.py", line 2786, in training_step
    loss = self.compute_loss(model, inputs)
  File "/mnt/disk3/wangyi/transformers/src/transformers/trainer.py", line 2818, in compute_loss
    outputs = model(**inputs)
  File "/mnt/disk1/wangyi/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/disk3/wangyi/peft/src/peft/peft_model.py", line 724, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/mnt/disk1/wangyi/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/disk1/wangyi/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/mnt/disk1/wangyi/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

**Review by younesbelkada — COMMENTED** [review]
This sounds very good to me, could you share a small reproducible snippet of the original issue? 🙏

**Comment by sywangyi** [comment]
image

**Comment by sywangyi** [comment]
the original logic is attached, failing....
you should move get_peft_model under smart_tokenizer_and embedding_resize.

**Comment by sywangyi** [comment]
https://github.com/tatsu-lab/stanford_alpaca/blob/main/train.py original code

**Comment by pacman100** [comment]
Hello @sywangyi, I am bit confused wrt PR.
1.  When one resizes the embedding layer and if that and final lm_head isn't trained then the model won't know/generate the new added tokens. 
2. Also, this has to be done before wrapping the model in PEFT as this is something out of scope of PEFT.

**Comment by sywangyi** [comment]
yes, @pacman100 this resize of embedding layer should be in full model finetune, not in peft model finetune. since the peft will not save the new generated token.

**Pull request closed without merging**
