### PR TITLE
try to fix Zero3 Memory Leak following @tohtana idea

### PR DESCRIPTION
**Pull request by dumpmemory**
here i am following @tohtana 's modification from https://github.com/microsoft/DeepSpeed/issues/3002 to fix https://github.com/huggingface/peft/issues/161 .  it worked with deepspeed 0.9.1 and torch 2.0.  Thanks for @tohtana 's help.

### CODE REVIEW

**Review by pacman100 — COMMENTED** [review]
Hello @dumpmemory, great work getting this issue solved from DeepSpeed and raising the fix here. Could you apply the fix to all places in lora and adalora wherein F.linear is being used . That would solve the issue in all places

**Comment by aashay96** [comment]
When will this be deployed?

**Review by pacman100 — COMMENTED** [review]
Thank you @dumpmemory for iterating, LGTM! 🤗

Could you run `make style` and `make quality` to fix the quality issues?

**Comment by pacman100** [comment]
Hello, @dumpmemory, there are still some code quality issues. Please resolve them to go ahead with the PR

**Comment by pacman100** [comment]
Hello, is this PR still required? As the DeepSpeed team fixed it in their codebase

**Pull request closed without merging**
