### PR TITLE
Improving error message when users pass layers_to_transform and layers_pattern

### PR DESCRIPTION
**Pull request by JINO-ROHIT**
This tries to add some verbose message when users pass layers_to_transform and layers_pattern addressing point 3 in #2155.

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
@JINO-ROHIT Please let me know if the PR is ready for review (always ping me if it's ready).

**Comment by BenjaminBossan** [comment]
Wait, how is this PR different from #2159?

**Comment by JINO-ROHIT** [comment]
yeah actually #2159 simply adds the check if 

```
if self.layers_to_transform is not None and self.layers_pattern is None:
            raise ValueError(
                "When `layers_to_transform` is specified, `layers_pattern` must also be specified. "
            )
```

This PR is making the error message better logging for layers_transform and layers_pattern if specified, this commit basically - [1f26074](https://github.com/huggingface/peft/pull/2164/commits/1f2607468cca12aab63104df71f413dd576f8384)

Looks weird that the other commits are being shown here

**Comment by BenjaminBossan** [comment]
> Looks weird that the other commits are being shown here

Yes, I can't really review this PR because of that. Probably it's easiest to just open a new PR and ensuring it only contains the commit intended for that PR.

**Comment by JINO-ROHIT** [comment]
sure

**Pull request closed without merging**
