### PR TITLE
Fix num layers of mlp prompt encoder

### PR DESCRIPTION
**Pull request by jungwhank**
Compared to the prompt encoder based on NeMO code, num_layers do not seem to be applied in MLP layers.
please let me know if it is intended.

### CODE REVIEW

**Review by pacman100 — COMMENTED** [review]
As "exactly 2 layers is recommended", removed the support for more layers than that

**Comment by jungwhank** [comment]
Thanks for letting me know that it was intended. I think the `num_encoder_layers` in the config might be a bit confusing when using MLP, so it would be nice to have a message or assertion about that. 
Additionally, thanks for the great library.

**Comment by pacman100** [comment]
Hello @jungwhank, Thank you! PR #149 should resolve this by raising a warning

**Comment by jungwhank** [comment]
@pacman100 Thanks! I'll close the PR.

**Pull request closed without merging**
