### PR TITLE
fix arguments for PiSSA preprocess

### PR DESCRIPTION
**Pull request by keakon**
Fix two bugs:
1. The `ArgumentParser` does not have a `help` argument.
2. The `--output_dir` argument is missing.

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
@keakon I think your latest commit made it worse :) Your first commit was almost good, I think it was just missing one more empty line between imports and code, there should always be two empty lines.

**Comment by keakon** [comment]
> @keakon I think your latest commit made it worse :) Your first commit was almost good, I think it was just missing one more empty line between imports and code, there should always be two empty lines.

I tried running `make style`, and it seems I missed a blank line the first time.

**Review by BenjaminBossan — APPROVED** [review]
Thanks a lot for this fix, LGTM.

**Comment by BenjaminBossan** [comment]
Pinging @fxmeng who added PiSSA, just in case. If there is no response, I'll merge at the end of the week.

**Comment by BenjaminBossan** [comment]
Thanks again @keakon. We didn't hear back by the end of the week, so I'll just go ahead and merge this now.

**Pull request merged**
