### PR TITLE
FIX: Multitask prompt tuning with other tuning init

### LINKED ISSUE #1082: 'Embedding' object has no attribute 'device' for MPT
I followed the test process of MPT notebook, but encountered an error during target training: 'Embedding' object has no attribute 'device'. I want to ask how to solve this.

### PR DESCRIPTION
**Pull request by BenjaminBossan**
~~This is WIP, do not merge.~~

~~I attempted to fix #1082. While adding tests for the bug, I discovered that I could not make prompt_tuning_init != RANDOM to work. Maybe I'm using it wrong, but I'm not sure what to change.~~

Tests are now passing, this is ready for review @pacman100 @younesbelkada

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
ping @mayank31398

**Comment by BenjaminBossan** [comment]
Another friendly ping @mayank31398

**Comment by mayank31398** [comment]
oops, hey @BenjaminBossan
will take a look over the weekend

**Comment by mayank31398** [comment]
```shell
FAILED tests/test_multitask_prompt_tuning.py::MultiTaskPromptTuningTester::test_generate_text_1_AVERAGE_SOURCE_TASKS - ValueError: task_ids cannot be None
FAILED tests/test_multitask_prompt_tuning.py::MultiTaskPromptTuningTester::test_generate_text_2_EXACT_SOURCE_TASK - ValueError: task_ids cannot be None
FAILED tests/test_multitask_prompt_tuning.py::MultiTaskPromptTuningTester::test_generate_text_3_ONLY_SOURCE_SHARED - ValueError: task_ids cannot be None
```
is this not expected?
these methods require task_ids parameter for forward pass or generate function

**Comment by BenjaminBossan** [comment]
Gentle ping @mayank31398

**Comment by mayank31398** [comment]
Screenshot 2024-02-06 at 12 14 47 PM
@BenjaminBossan It seems to be working fine for me.
Ignore the failing test for bf16 (I am on a Mac and that doesn't support bf16).

**Comment by mayank31398** [comment]
I merge main branch into the branch and then ran it. The test seems to pass for me

**Comment by mayank31398** [comment]
Can you try my branch: https://github.com/mayank31398/peft/tree/fix-multitask-prompt-tuning-other-inits

**Comment by BenjaminBossan** [comment]
> I merge main branch into the branch and then ran it. The test seems to pass for me

Strange. I also merged the main branch and as you can see, CI  is still red. The failing tests are:

```
FAILED tests/test_multitask_prompt_tuning.py::MultiTaskPromptTuningTester::test_generate_text_3_ONLY_SOURCE_SHARED - ValueError: task_ids cannot be None
FAILED tests/test_multitask_prompt_tuning.py::MultiTaskPromptTuningTester::test_generate_text_0_TEXT - OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
FAILED tests/test_multitask_prompt_tuning.py::MultiTaskPromptTuningTester::test_generate_text_1_AVERAGE_SOURCE_TASKS - ValueError: task_ids cannot be None
FAILED tests/test_multitask_prompt_tuning.py::MultiTaskPromptTuningTester::test_generate_text_2_EXACT_SOURCE_TASK - ValueError: task_ids cannot be None
```

**Comment by mayank31398** [comment]
@BenjaminBossan ok, I did a fresh conda env install and now I am able to replicate your issue
For some reason, it was not picking my source install.
Fixing this right now :)

**Comment by mayank31398** [comment]
@BenjaminBossan fixed. Opened PR against your branch: https://github.com/BenjaminBossan/peft/pull/8

**Comment by mayank31398** [comment]
@BenjaminBossan @pacman100 can we merge this soon? 🤗

**Comment by BenjaminBossan** [comment]
Still waiting for a review :D

**Review by pacman100 — APPROVED** [review]
Thank you @BenjaminBossan and @mayank31398 for fixing Multitask prompt tuning to work with non-random init configs!

**Pull request merged**
