### PR TITLE
[tests] skip some tests for XPU devices

### PR DESCRIPTION
**Pull request by faaany**
eetq/hqq/aqlm doesn't support XPU yet. So we want to skip them for now.

### CODE REVIEW

**Review by BenjaminBossan — APPROVED** [review]
Thanks for the update to the tests. We'll (hopefully) also add torchao and optimum-quanto support in the near future. Should those also be skipped on XPU?

**Comment by yao-matrix** [comment]
> Thanks for the update to the tests. We'll (hopefully) also add torchao and optimum-quanto support in the near future. Should those also be skipped on XPU?

Yes, we can skip as of now. And torchao and optimum-quanto is in our priority enabling list, once they are enabled in xpu, we will submit PR to remove the skipping.

**Comment by faaany** [comment]
If these tests live in a separate file or folder, we could also ignore them using  `pytest --ignore` to save code in codebase.

**Comment by BenjaminBossan** [comment]
I agree that the organization of tests is a bit messy in PEFT, but let's keep them as is for now, I don't think these few extra lines of code are hurting.

**Pull request merged**
