### PR TITLE
 Fix PeftMixedModel docstring #1824 #1 

### PR DESCRIPTION
**Pull request by namanvats**
What does this PR Do?

This PR removes the redundant import in the PeftMixedModel example and was confusing as raised here: #1824 
Import was not required for the example, so removed it.

Fxies: #1824

### CODE REVIEW

**Comment by namanvats** [comment]
@BenjaminBossan Please review

**Review by younesbelkada — COMMENTED** [review]
Thanks for the contribution ! Can you run the styling checks? `make style && make quality`

**Comment by namanvats** [comment]
@younesbelkada `make style && make quality` Received confirmation as `All Checks Passed `

**Comment by namanvats** [comment]
@younesbelkada Checking the failures will update once fixed, looks to be some issue here in Makefile
`style:
	ruff $(check_dirs) --fix
	ruff format $(check_dirs)
	doc-builder style src/peft tests docs/source --max_len 119`

**Pull request closed without merging**
