### PR TITLE
Glora implementation from https://github.com/Arnav0400/ViT-Slim/tree/master/GLoRA

### PR DESCRIPTION
**Pull request by viliamvolosv**
More ingormation https://arxiv.org/abs/2306.07967

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
Thanks for this PR to add GLoRA to PEFT. I haven't done a full review of the PR yet. Before this, do you have an example that uses GLoRA and shows that it works well? Maybe you could check one of the LoRA examples that we have and create a GLoRA example based on it so that we can compare results.

Furthermore, we'll have to add documentations and tests to this PR. Do you think you could work on those?

**Comment by viliamvolosv** [comment]
> l

At this moment  - im testing GLORa on LLM.
Afnter that  i nake care examples and docs
But now i have some problem with Glora - whe i fix this issues i start to wok on doc and examples

**Comment by viliamvolosv** [comment]
@BenjaminBossan May be you can look on error in GLORA ?
issue https://github.com/Arnav0400/ViT-Slim/issues/17

im not a Python develeper, and not LLM developer -  ith just pet project for me

**Comment by BenjaminBossan** [comment]
I replied in the linked thread.

**Comment by viliamvolosv** [comment]
@BenjaminBossan 
How do you think  it is normal to use  this bases classes 
class GLoraModel(torch.nn.Module):
class GLoraConfig(PeftConfig):

maybe batter user other bases classes ?


and in base code i saw this Linear4bit(torch.nn.Module, LoraLayer): - it multiple inheritance ?

**Comment by BenjaminBossan** [comment]
For `GLoraModel`, you should inherit from `peft.tuners.tuners_utils.BaseTuner`. You could also inherit from `peft.tuners.lycoris_utils.LycorisTuner`, which provides some more methods already implemented for you, check e.g. https://github.com/huggingface/peft/blob/main/src/peft/tuners/loha/model.py.

For the config, `PeftConfig` is correct, unless you go with `LycorisTuner`, in which case you should use `peft.tuners.lycoris_utils.LycorisConfig`.

For the layers, yes, we use multiple inheritance. You should have a `GLoraLayer` that inherits from `peft.tuners.tuners_utils.BaseTunerLayer` and then the concrete implementations, like `glora.Linear`, should inherit from `nn.Module, GLoraLayer`.

**Comment by viliamvolosv** [comment]
Thx fot advice - il do as you say.
Alsow i  add example for GLORA .
How i have 2 request:
1 - pls check example  glora_finetuning.py. Maybe i need to use other models and data sets. and over all quality
2 - As i say im not Python and LLM developer, its had for me. May be you can run example and fix some bugs ? and then i procede

**Comment by BenjaminBossan** [comment]
> 1 - pls check example glora_finetuning.py. Maybe i need to use other models and data sets. and over all quality

I'm currently in another office, I can check the example next week when I'm back. In general, however, I would recommend that you pick one of the [existing examples](https://github.com/huggingface/peft/tree/main/examples), e.g. the [VeRA example](https://github.com/huggingface/peft/blob/main/examples/sequence_classification/VeRA.ipynb), and switch it up to use GLoRA instead. Or you could try to reproduce one of the GLoRA examples from the paper. I'm not sure what the example in this PR is based on or if you came up with it yourself.

> As i say im not Python and LLM developer

Just so you know, there is still a bit of work to do on this PR before it can be merged, e.g. documentation and especially unit tests. This will not be an easy entry into this topic. My goal is not to discourage you, but to let you know that this is quite a big task to get started on this topic.

**Comment by BenjaminBossan** [comment]
Yes, we can help with this PR, but you may have to wait a bit for me to find some spare time. Could you please describe more specifically what problems you are facing right now?

**Comment by viliamvolosv** [comment]
> Yes, we can help with this PR, but you may have to wait a bit for me to find some spare time. Could you please describe more specifically what problems you are facing right now?

Now i stuck on this error 
`  File "/home/guest/peft/examples/glora_finetuning/glora_finetuning.py", line 125, in <module>
    training_function()
  File "/home/guest/peft/examples/glora_finetuning/glora_finetuning.py", line 91, in training_function
    trainer = SFTTrainer(
  File "/home/guest/.local/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/guest/.local/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 254, in __init__
    model = get_peft_model(model, peft_config)
  File "/home/guest/.local/lib/python3.10/site-packages/peft/mapping.py", line 174, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](
  File "/home/guest/.local/lib/python3.10/site-packages/peft/peft_model.py", line 1468, in __init__
    super().__init__(model, peft_config, adapter_name, **kwargs)
  File "/home/guest/.local/lib/python3.10/site-packages/peft/peft_model.py", line 150, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/home/guest/.local/lib/python3.10/site-packages/peft/tuners/glora/model.py", line 94, in __init__
    super().__init__(model, config, adapter_name)
  File "/home/guest/.local/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 166, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/home/guest/.local/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 412, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, current_key=key)
  File "/home/guest/.local/lib/python3.10/site-packages/peft/tuners/glora/model.py", line 310, in _create_and_replace
    new_module = self._create_new_module(
  File "/home/guest/.local/lib/python3.10/site-packages/peft/tuners/glora/model.py", line 418, in _create_new_module
    new_module = dispatcher(target, adapter_name, glora_config=glora_config, **kwargs)
  File "/home/guest/.local/lib/python3.10/site-packages/peft/tuners/glora/model.py", line 464, in dispatch_default_glora
    new_module = Linear(target, adapter_name, target.in_features, target.out_features, **kwargs)
  File "/home/guest/.local/lib/python3.10/site-packages/peft/tuners/glora/layer.py", line 102, in __init__
    layer.reset_parameters()
  File "/home/guest/.local/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 109, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/home/guest/.local/lib/python3.10/site-packages/torch/nn/init.py", line 459, in kaiming_uniform_
    return tensor.uniform_(-bound, bound, generator=generator)
RuntimeError: "check_uniform_bounds" not implemented for 'Byte'`

**Comment by viliamvolosv** [comment]
Problem for me tha i took for example LORA implimentation  - and this implementation is very hard ))
im stuck on Liner initialization
image

**Comment by viliamvolosv** [comment]
for reference - this is initial implimentation for old peft
https://github.com/huggingface/peft/compare/main...Arnav0400:peft:main

**Comment by BenjaminBossan** [comment]
Okay, thanks for providing more details. I'll take a look at this to see what's causing the error, but probably won't have time earlier than next week.

**Comment by viliamvolosv** [comment]
@BenjaminBossan  I close this fork, because i create more cliner version of Glora
pls see this https://github.com/huggingface/peft/pull/1880

**Pull request closed without merging**
