### PR TITLE
fix the fsdp peft autowrap policy

### PR DESCRIPTION
**Pull request by pacman100**
### What does this PR do?
1. In PR https://github.com/huggingface/accelerate/pull/2662, the static method was removed as other classes also required it and hence was made a function to avoid code duplication in each class. This PR updates the usage of that function.

### CODE REVIEW

**Review by BenjaminBossan — COMMENTED** [review]
This would only work with the latest accelerate version, right? So this would require all PEFT users to upgrade accelerate. Can we instead make this backwards compatible?

**Comment by pacman100** [comment]
> This would only work with the latest accelerate version, right? So this would require all PEFT users to upgrade accelerate. Can we instead make this backwards compatible?

Done

**Comment by BenjaminBossan** [comment]
@pacman100 After merging #1697, the doc built should be fixed, so merging main should fix the CI.

**Review by BenjaminBossan — APPROVED** [review]
Thanks for the fix, LGTM.

**Pull request merged**
