### PR TITLE
example on converting PEFT+INT8 trained model to ONNX for faster inference

### PR DESCRIPTION
**Pull request by pacman100**
### What does this PR do?
1. Adds an example on converting PEFT+INT8 trained model to ONNX for faster inference. The example depicted is for Whsiper-large-V2 model.

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thanks a lot for this great addition! 
I think it's better to add titles etc just to explain the context to the user, I would also advocate creating a handy script so that a user can convert the model out of the box with no need to run all the cells of the notebook, wdyt?

**Review by sayakpaul — APPROVED** [review]
This is 🔥 

Some minor things we can do to spice things up:

* Instead of the elaborate comments, let's maybe use the markdown cells and have some headings and one-liners there. For notebooks, I find them easier to follow along. 
* Throw in some numbers on optimization. How much speed-up can one expect based on this? 

I agree with @younesbelkada that adding a standalone script would be quite beneficial for the users.

**Review by sam-at-pieces — APPROVED** [review]

**Comment by sayakpaul** [comment]
@pacman100 good to merge no?

**Comment by pacman100** [comment]
Hello, it does merge post the pr #117, could you provide an minimal example we can run if you are still encountering the issue with latest PEFT V0.2.0?

**Comment by pacman100** [comment]
Hello @ccasimiro88, I'm unable to reproduce error using the latest main branch of PEFT, could you please try it and let us know.

Code:
```
import torch
from peft import LoraConfig, PeftConfig, PeftModelForCausalLM
from transformers import AutoModelForCausalLM, AutoTokenizer, BloomForCausalLM


peft_model_id = "mrm8488/Alpacoom"

peft_config = PeftConfig.from_pretrained(peft_model_id)


tokenizer = AutoTokenizer.from_pretrained("bigscience/bloom-7b1")

base_model = AutoModelForCausalLM.from_pretrained(
    peft_config.base_model_name_or_path,
    load_in_8bit=False,
    torch_dtype=torch.float16,
    device_map={"": "cpu"},
)


lora_model = PeftModelForCausalLM.from_pretrained(
    base_model,
    peft_model_id,
)


lora_model.eval()
lora_model.half()
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig

# Based on the inference code by `tloen/alpaca-lora`
def generate_prompt(instruction, input=None):
    if input:
        return f"""Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
### Instruction:
{instruction}
### Input:
{input}
### Response:"""
    else:
        return f"""Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
{instruction}
### Response:"""

def generate(
        instruction,
        input=None,
        temperature=0.1,
        top_p=0.75,
        top_k=40,
        num_beams=4,
        **kwargs,
):
    prompt = generate_prompt(instruction, input)
    inputs = tokenizer(prompt, return_tensors="pt")
    input_ids = inputs["input_ids"].cuda()
    generation_config = GenerationConfig(
        temperature=temperature,
        top_p=top_p,
        top_k=top_k,
        num_beams=num_beams,
        **kwargs,
    )
    with torch.no_grad():
        generation_output = lora_model.generate(
            input_ids=input_ids,
            generation_config=generation_config,
            return_dict_in_generate=True,
            output_scores=True,
            max_new_tokens=256,
        )
    s = generation_output.sequences[0]
    output = tokenizer.decode(s)
    return output.split("### Response:")[1].strip().split("Below")[0]

instruction = "Tell me about alpacas"

print("Instruction:", instruction)
print("Response:", generate(instruction))

```

Output:
```
Instruction: Tell me about alpacas
Response: Alpacas are a type of llama-like animal native to the Andes Mountains of South America. They are known for their long, fluffy coats, which are used for clothing, bedding, and other items. Alpacas are also used for their wool, which is soft and warm.
```

**Comment by ccasimiro88** [comment]
Hi @pacman100, I installed the repo from source (main branch) and now it works. Many thanks!

**Pull request closed without merging**
