### PR TITLE
Add local saving for whisper largev2 example notebook

### PR DESCRIPTION
**Pull request by alvanli**
I don't usually directly push the model to hub and I had some trouble with saving the model locally when I relied on the trainer checkpoints in the sample notebook. <br/>
Added a callback to save adapter to checkpoints, using the code from here: https://github.com/huggingface/peft/issues/96

### CODE REVIEW

**Review by pacman100 — APPROVED** [review]
@alvanli, Thanks a lot for adding this! 🤗

**Comment by jordancole21** [comment]
Hey! just implemented this in my flan t5 code! What code would I use to load the model in from the saved checkpoint?

**Comment by alvanli** [comment]
for Whisper, it was something like this
```
from peft import PeftModel, PeftConfig
from transformers import WhisperForConditionalGeneration, Seq2SeqTrainer

peft_model_id = "./<output_dir>/checkpoint-12000"
peft_config = PeftConfig.from_pretrained(peft_model_id)
model = WhisperForConditionalGeneration.from_pretrained(
    peft_config.base_model_name_or_path, load_in_8bit=True, device_map="auto"
)
model = PeftModel.from_pretrained(model, peft_model_id)
```

**Comment by jordancole21** [comment]
> from peft import PeftModel, PeftConfig
> from transformers import WhisperForConditionalGeneration, Seq2SeqTrainer
> 
> peft_model_id = "./<output_dir>/checkpoint-12000"
> peft_config = PeftConfig.from_pretrained(peft_model_id)
> model = WhisperForConditionalGeneration.from_pretrained(
>     peft_config.base_model_name_or_path, load_in_8bit=True, device_map="auto"
> )
> model = PeftModel.from_pretrained(model, peft_model_id)

Thank you! That worked perfectly!

**Pull request merged**
