### PR TITLE
Support for LLaMA models

### PR DESCRIPTION
**Pull request by zphang**
Can be merged after https://github.com/huggingface/transformers/pull/21955

### CODE REVIEW

**Comment by zoidbb** [comment]
Have you tested this? In my local testing previously, implementing this exact change, I ran into an issue where the trainers didn't like not having a pad token in the tokenizer.

**Comment by zphang** [comment]
> Have you tested this? In my local testing previously, implementing this exact change, I ran into an issue where the trainers didn't like not having a pad token in the tokenizer.

Yes, but I tested with my own data pipeline/data collator.

**Comment by zoidbb** [comment]
> @zoidbb does adding:
> 
> ```python
> tokenizer.pad_token = tokenizer.eos_token
> ```
> 
> helps solving your issue?

Oddly not, I tried this and it still complained. I'll provide more details this evening when I'm done with work.

**Comment by tloen** [comment]
@zoidbb you may also need:

```
tokenizer.pad_token_id = tokenizer.eos_token_id
```

**Review by pacman100 — APPROVED** [review]
Thank you @zphang for adding this! 🤗

**Pull request merged**
