### PR TITLE
Cast to fp32 if using bf16 weights on cpu during `merge_and_unload`

### PR DESCRIPTION
**Pull request by snarayan21**
Should address https://github.com/huggingface/peft/issues/1977

### CODE REVIEW

**Comment by snarayan21** [comment]
@BenjaminBossan Our team found this bug through LoRA runs that were hanging for a very long time on certain CPU types and addressed it with this simple fix. would be great if you could take a look. Thanks!

**Comment by BenjaminBossan** [comment]
Thanks for working on this fix. I think this should be okay to merge, but I would like to check if I can replicate the slowness. Do you have an example that I could check?

**Comment by snarayan21** [comment]
It's dependent on the CPU, but instantiating any LoraModel, converting it to fp16 (should be fast) and bf16 (should be slow), and calling`model.merge_and_unload()` should do the trick...

**Comment by snarayan21** [comment]
Actually @BenjaminBossan here's a script which worked for me. Running locally on my mac, I got:
```
Merge and unload with dtype torch.float32 took 0.13617515563964844 seconds
Merge and unload with dtype torch.bfloat16 took 8.84065294265747 seconds
Merge and unload with dtype torch.float16 took 0.15977191925048828 seconds
```
Script:
```
from transformers import AutoModelForCausalLM
from peft import LoraConfig, get_peft_model
import time
import torch

model_id = "facebook/opt-350m"


def merge_adapters(dtype):
    model = AutoModelForCausalLM.from_pretrained(model_id)
    config = LoraConfig(r=256)
    model = get_peft_model(model, config)

    model = model.to(dtype=dtype)

    start = time.time()
    model = model.merge_and_unload()
    end = time.time()

    print(f'Merge and unload with dtype {dtype} took {end - start} seconds')

if __name__ == '__main__':
    merge_adapters(torch.float32)
    merge_adapters(torch.bfloat16)
    merge_adapters(torch.float16)
```

**Comment by BenjaminBossan** [comment]
Thanks for providing the example. On one machine, I could not see any slowdown with bf16, on the other there was a factor of 100.

Regarding the comment above the code:

```
        # In case users wants to merge the adapter weights that are in
        # (b)float16 while being on CPU, we need to cast the weights to float32, perform the merge and then cast back to
        # (b)float16 because the `@` and matmul operation in general is not supported in torch + cpu + fp16/bf16.
        cast_to_fp32 = device.type == "cpu" and (dtype == torch.float16 or dtype == torch.bfloat16)
```

it is not quite correct anymore, right? Originally, we had to cast to fp32 because there was an error with fp16 on CPU (which I think is fixed in newer PyTorch versions). Would it make sense to add a comment about accelerating the operation on some CPUs?

**Comment by snarayan21** [comment]
Sure, let me change that.

**Comment by snarayan21** [comment]
@BenjaminBossan updated!

**Review by BenjaminBossan — APPROVED** [review]
Thanks for this improvement, LGTM.

**Comment by snarayan21** [comment]
@BenjaminBossan when will the next release be?

**Comment by BenjaminBossan** [comment]
> when will the next release be?

Sorry, no release soon, as we had a release just last week. You could install from `main` (optionally fixing the hash) if you need this right now.

**Pull request merged**
